baseURL = 'https://rholden.dev/'
languageCode = 'en-us'
title = 'rholden.dev'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
	disableXML = true
	minifyOutput = true

[module]
	[[module.imports]]
		path = 'github.com/adityatelange/hugo-PaperMod'

[params]
	env = 'production'
	title = 'rholden.dev'
	description = 'A blog about whatever'
	keywords = ['software', 'engineering', 'kubernetes', 'devops', 'pulumi', 'llms', 'ai', 'homelab']
	author = 'Robert Holden'
	DateFormat = 'January 2, 2006'
	defaultTheme = 'auto'

	ShowReadingTime = true
	ShowShareButtons = false
	ShowPostNavLinks = true
	ShowBreadCrumbs = true
	ShowCodeCopyButtons = false
	ShowWordCount = true
	ShowRssButtonInSectionTermList = true
	UseHugoToc = true
	disableSpecial1stPost = false
	disableScrollToTop = false
	comments = false
	hidemeta = false
	hideSummary = false
	showtoc = false
	tocopen = false
	
	[params.assets]
		disableHLJS = false
		disableFingerprinting = false
		# favicon = 'https://rholden.dev/apple-touch-icon.png'
		# favicon16x16 = 'https://rholden.dev/apple-touch-icon.png'
		# favicon32x32 = 'https://rholden.dev/apple-touch-icon.png'
		# apple_touch_icon = 'https://rholden.dev/apple-touch-icon.png'
		# safari_pinned_tab = 'https://rholden.dev/apple-touch-icon.png'
	
	[params.label]
		text = 'rholden.dev'
		# icon = 'https://rholden.dev/apple-touch-icon.png'
		# iconHeight = 35

	[params.fuseOpts]
		isCaseSensitive = false
		shouldSort = true
		location = 0
		distance = 1000
		threshold = 0.4
		minMatchCharLength = 0
		limit = 10
		keys = ['title', 'permalink', 'summary', 'content']

	[params.profileMode]
		enabled = false
		title = 'rholden.dev'
		subtitle = 'A blog about whatever'
		# imageUrl = 'https://rholden.dev/apple-touch-icon.png'
		# imageWidth = 120
		# imageHeight = 120
		# imageTitle = 'my image'
		[[params.profileMode.buttons]]
			name = 'Posts'
			url = 'posts'
		[[params.profileMode.buttons]]
			name = 'Tags'
			url = 'tags'

[menu]
	[[menu.main]]
		name = "Categories"
		url = "/categories/"
		weight = 10
	[[menu.main]]
		name = "Tags"
		url = "/tags/"
		weight = 20
	[[menu.main]]
		name = "Search"
		url = "/search/"
		weight = 30

pygmentsUseClasses = true

[markup]
	[markup.highlight]
		noClasses = false
